---
- name: Load distro-specific vars
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- include_tasks: nginx.yml

- name: 'Download mattermost binary'
  get_url:
    url: "{{ mattermost_url }}"
    dest: /tmp/
    mode: '0644'
    checksum: "{{ mattermost_checksum }}"
  when: use_get_url

- name: Download mattermost binary (using wget because get_url fails if system python is older than 2.7.5)
  command: "wget \"{{ mattermost_url }}\""
  args:
    chdir: /tmp/
    creates: "/tmp/{{ mattermost_url | basename }}"
    warn: false
  when: not use_get_url

- name: Create user to run mattermost service.
  user:
    name: "{{ mattermost_user }}"
    system: yes
    createhome: no

- name: Unpack mattermost archive.
  unarchive:
    src: "/tmp/{{ mattermost_url | basename }}"
    dest: /opt
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_user }}"
    remote_src: true
  args:
    creates: /opt/mattermost/bin/platform

- name: Apply mattermost config.json template
  template:
    src: mattermost-config.json.j2
    dest: /opt/mattermost/config/config.json
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_user }}"
    mode: '0644'
    backup: "{{ mattermost_backup | default('yes') }}"
  notify:
    - restart mattermost

- debug: var=ansible_service_mgr verbosity=1
- debug: var=ansible_virtualization_type verbosity=1
- name: Docker | use systemv as init system
  set_fact:
    init_system: systemv
    mattermost_service_use: sysvinit
  when: >
    (ansible_virtualization_type is defined and (ansible_virtualization_type == "docker"))
- debug: var=init_system verbosity=1
- include_tasks: "init/{{ init_system }}.yml"

- include_tasks: selinux.yml
  when: selinux_enable

- name: Symlink log directory to /var/log
  file:
    src: /opt/mattermost/logs
    dest: /var/log/mattermost
    state: link

- name: Ensure Mattermost service is enabled and started
  service:
    name: mattermost
    enabled: yes
    state: started
    use: "{{ mattermost_service_use | default('auto') }}"
  changed_when: mattermost_idempotence_changedwhen | default(omit)

- include_tasks: postconfig.yml

# vim:ft=ansible:
