---

- name: Change nginx cache directory permissions
  file:
    path: /var/cache/nginx
    state: directory
    owner: nginx
    group: nginx
    recurse: yes
  when: ansible_os_family == "RedHat"

- name: Apply nginx config template
  template:
    src: "{{ mattermost_nginx_template | default('nginx-mattermost.conf.j2') }}"
    dest: /etc/nginx/conf.d/mattermost.conf
  notify: restart nginx
# vim:ft=ansible
