---

- name: Validate nginx cache directory permissions
  file:
    path: /var/cache/nginx
    state: directory
    owner: "{% if ansible_os_family == 'RedHat' %}nginx{% else %}www-data{% endif %}"
    group: "{% if ansible_os_family == 'RedHat' %}nginx{% else %}www-data{% endif %}"

- name: Apply nginx config template
  template:
    src: "{{ mattermost_nginx_template | default('nginx-mattermost.conf.j2') }}"
    dest: /etc/nginx/conf.d/mattermost.conf
  notify: restart nginx
# vim:ft=ansible
