---
# handlers file for mattermost

- name: reload systemd
  systemd:
    daemon_reload: yes
  when: >
    not (ansible_virtualization_type is defined and (ansible_virtualization_type == "docker"))

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart postgres
  service:
    name: postgresql
    state: restarted

- name: restart mattermost
  service:
    name: mattermost
    state: restarted

# vim: ft=ansible:    
