---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance
    #image: ${MOLECULE_DISTRO:-ubuntu:18.04}
    image: "geerlingguy/docker-${MOLECULE_DISTRO//:}-ansible:latest"
    #image: docker.io/pycontribs/centos:7
    #pre_build_image: true
    # env:
    #   http_proxy: ${http_proxy}
    #   https_proxy: ${https_proxy}
    #   no_proxy: ${no_proxy}
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 0
verifier:
  name: ansible
