---
- name: Converge
  hosts: all
  roles:
    - role: geerlingguy.postgresql
    - role: juju4.harden-nginx
    - role: juju4.mattermost
  pre_tasks:
    - name: Ubuntu Bionic+ | Enforce python3 for ansiblr
      set_fact:
        ansible_python_interpreter: /usr/bin/python3
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 18)
