---

- name: Create mattermost systemd service
  template:
    src: init/systemd.j2
    dest: /etc/systemd/system/mattermost.service
    owner: root
    group: root
    mode: 0664

- name: Ensure override folder exists
  file:
    dest: /etc/systemd/system/mattermost.service.d
    state: directory
    mode: '0755'

# if issue, check /var/log/audit/audit.log
- name: Review mattermost systemd options
  template:
    src: systemd-override.conf.j2
    dest: /etc/systemd/system/mattermost.service.d/override.conf
    mode: '0644'
  notify:
    - reload systemd
    - restart mattermost

# vim:ft=ansible:
